### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by xxrlzzz** [keyou/chromium_demo#1]
Nice work your have been made, since `base/message_loop/message_loop.h` has been delete in current version of chromium. (and other module this demo depends) the most module can't compile. Will you consider fix the old depends on your code example?

**Comment by xxrlzzz** [comment]
sorry for not see the version tag, but I think `base::test::TaskEnvironment` to replace `base::MessageLoop` maybe optional

**Comment by keyou** [comment]
Thanks for the first issue,I am considering making the project support the new version,a few months later.
