### ISSUE TITLE
期待修复View&Service相关Demo

### ISSUE THREAD

**Issue by ManonLoki** [keyou/chromium_demo#15]
建议View提供最小化Demo 分别为布局，事件，以及组件实现三种

**Comment by keyou** [comment]
很好的建议。

关于View，目前的 View 只是最简单的 demo，在它之上再学习其他的 view 组件会简单很多，因此这里的 demo 应该已经起到了指引新人入门的作用，当然如果能有更丰富的 demo 更好，只不过可能需要更多的时间了。

关于 Service 由于91版本的 ServiceManager 被移除了，所以目前的 Service demo 面临大改，目前无法给出确切的升级时间。

一个人精力有限，如果其他人看到这个回答，欢迎提供帮助，一起迁移到 91。

**Comment by keyou** [comment]
mojo services 的 demo 已经迁移到 v91 了。不过新版的 chromium 已经不使用 demo_services 中演示的用法了，不建议继续学习这个 demo。

**Comment by keyou** [comment]
demo_views 已经迁移到 v91 ✅。
