### ISSUE TITLE
build issue with //content:dev_ui_content_resources

### ISSUE THREAD

**Issue by arskama** [keyou/chromium_demo#36]
Hi,

I wanted to try our demo_mojo.
I followed all the instrusctions from the README, and ended up when running ninja

ERROR Unresolved dependencies.
//demo/demo_shell:pak(//build/toolchain/linux:clang_x64)
  needs //content:dev_ui_content_resources(//build/toolchain/linux:clang_x64)

Looking at cs.chromium, I didn't find many occurences.

**Comment by keyou** [comment]
What is your build command?

**Comment by arskama** [comment]
autoninja -C out/Default chrome demo_mojo

**Comment by arskama** [comment]
Not sure how you got that to compile since this patch was introduced in May.
https://chromium-review.googlesource.com/c/chromium/src/+/4500969

Also after this was solved, I got some compilation errors.
demo/demo_callback/demo_callback_repeating.cc:1:10: fatal error: 'base/bind.h' file not found
Nowadays bind.h is under //base/functional/

**Comment by keyou** [comment]
Successfully building the project requires that both chromium and the demo project are switched to the correct branch. You get compile error of  `demo_callback ` but you are building `demo_mojo`, which is confused. 

So please check:
1. What branch of chromium and the demo you are using?
2. Does your chromium can build success alone?
3. Does demo_exe can build success? Use `autoninja -C out/Default demo_exe`
4. Build `demo_mojo` use `autoninja -C out/Default demo_mojo`.

**Comment by arskama** [comment]
Chromium project.
commit ce336c4a53c0d3379b5eda1a73b51c7ebababcd8 (HEAD -> demo_test, tag: 120.0.6099.40)
Demo:
commit dc37cb392ee381c9e2bd8e5b3ec2ac033b9971c7 (HEAD -> c/120.0.6099, origin/c/120.0.6099, origin/HEAD)

my chromium builds fine without changing the gn args.

**Comment by arskama** [comment]
For example: Demo shell [BUILD.gn](
 https://github.com/keyou/chromium_demo/tree/c/120.0.6099/demo_shell) for M120, was updated 9 month ago, so how can it take into account the [change](https://chromium-review.googlesource.com/c/chromium/src/+/4500969) from May?

**Comment by arskama** [comment]
autoninja -C out/Default demo_exe builds
autoninja -C out/Default demo_mojo does not

../../demo/demo_mojo/demo_mojo_multiple_process.cc:216:11: error: no member named 'ThreadTaskRunnerHandle' in namespace 'base'
  216 |     base::ThreadTaskRunnerHandle::Get()->PostDelayedTask(
      |     ~~~~~~^

With the following fix, it does
:
--- a/demo_mojo/demo_mojo_multiple_process.cc
+++ b/demo_mojo/demo_mojo_multiple_process.cc
@@ -213,7 +213,7 @@ void MojoProducer() {
     LOG(INFO) << "send: " << kMessage;
 
     // 延迟5s再次发送消息
-    base::ThreadTaskRunnerHandle::Get()->PostDelayedTask(
+    base::SingleThreadTaskRunner::GetCurrentDefault()->PostDelayedTask(

**Comment by arskama** [comment]
> Successfully building the project requires that both chromium and the demo project are switched to the correct branch. You get compile error of `demo_callback ` but you are building `demo_mojo`, which is confused.

I was trying to build the whole thing. Therefore!

**Comment by keyou** [comment]
Thanks for the reply. 
I check the project again, it turns out that M120 cannot be compiled. There must have been something wrong within the latest commit, I will check it out during this weekend or maybe you want to help fix it.

**Comment by keyou** [comment]
Most of the demos can be compiled with M120 now.
